<a href="https://colab.research.google.com/github/KrisnaBagus/ScientificComputing-LAB-/blob/main/SC_sesi_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sesi 1

In [1]:
print("Hello Word")

Hello Word


In [4]:
import time

print(time.ctime())

Thu Feb  6 04:41:43 2025


In [7]:
z = "Hello"
y = 20
c = 30.9
f = ["Apple", "Berry"]

z, y, c, f
print(z, y, c, f)

Hello 20 30.9 ['Apple', 'Berry']


In [9]:
o = int(1)
y = int(2.8)
z = int("3")
j = str(20)

o, y, z, j
print(o, y, z, j)

1 2 3 20


In [13]:
a = "Hello"
b = " World"
c = a + b

print(c)

Hello World


In [14]:
a = "Hello World"
print(a[1])

print(len(a))

e
11


In [18]:
b = "BINUS Univ"
print(b[2:5])

c = "BINUS Univ"
print(c[:5])

d = "BINUS Univ"
print(d[2:])


NUS
BINUS
NUS Univ


In [19]:
a = "Hello"
print(a.upper())

b = "Hello"
print(b.lower())

c = "Hello"
print(c.replace("H", "J"))

HELLO
hello
Jello


In [20]:
nama = "Sam"

x = 19

string = "nama saya {} umur {}"

print(string.format(nama, x))

nama saya Sam umur 19


In [22]:
nama = "Grace"
for i in enumerate(nama):
  print(i)

(0, 'G')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


In [29]:
def perbandingan (a,b):
  if a>b:
    print("a lebih dari b")
  elif a<b:
    print("a kurang dari b")
  else:
    print("a = b")

In [30]:
perbandingan (4,8)

a kurang dari b


In [31]:
i=1
while i<6:
  print(i)
  i += 1

1
2
3
4
5


In [35]:
i=1
for i in range(0,6):
  print(i)

0
1
2
3
4
5


In [40]:
for i in range(2,40):
  if i % 2==0:
    print(i, "Genap")
  else:
      print(i, "Ganjil")

2 Genap
3 Ganjil
4 Genap
5 Ganjil
6 Genap
7 Ganjil
8 Genap
9 Ganjil
10 Genap
11 Ganjil
12 Genap
13 Ganjil
14 Genap
15 Ganjil
16 Genap
17 Ganjil
18 Genap
19 Ganjil
20 Genap
21 Ganjil
22 Genap
23 Ganjil
24 Genap
25 Ganjil
26 Genap
27 Ganjil
28 Genap
29 Ganjil
30 Genap
31 Ganjil
32 Genap
33 Ganjil
34 Genap
35 Ganjil
36 Genap
37 Ganjil
38 Genap
39 Ganjil


In [42]:
import numpy as np

In [43]:
x = np.array([[1, 2, 3], [3, 6, 7]])
print(x)

[[1 2 3]
 [3 6 7]]


In [45]:
y = np.array([[8, 2, 9], [3, 5, 7]])
x + y


array([[ 9,  4, 12],
       [ 6, 11, 14]])

In [46]:
data = np.array([10, 9, 8, 7, 5, 6])
print("Rata-rata :", np.mean(data))
print("Maksimum :", np.max(data))
print("Minimum : ", np.min(data))
print("Standar Deviasi : ", np.std(data))

Rata-rata : 7.5
Maksimum : 10
Minimum :  5
Standar Deviasi :  1.707825127659933
